import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

export const metadata: Metadata = {
  title: 'The blog - This is a page made with Next.js',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang='en'>
      <p>HEADER</p>
      <body>
        <div className='bg-red-500'>{children}</div>
      </body>
      <p>FOOTER</p>
    </html>
  );
}
